config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root 'pages#index'
  resources :writes do
      resources :comments
  end
  resources :userparams


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :write
	belongs_to :user
end

app/models/genre.rb
class Genre < ApplicationRecord
	belongs_to :write

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :writes
         has_one :userparam
         has_many :comments
end

app/models/userparam.rb
class Userparam < ApplicationRecord
	belongs_to :user
	validates :firstname, :lastname, :age, presence: true

	validates  :age, numericality: { only_integer: true }
  validates_inclusion_of :age, :in => 18..45

	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/assets/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/write.rb
class Write < ApplicationRecord
	belongs_to :user
	validates :title, :firstheroy, :secondheroy, :aboutstory, :body, presence: true
	has_one :genre
	has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	before_action :set_write
   def new
    @comment = Comment.new
  end
  
  def create
    params[:comment][:user_id] = current_user.id
    params[:comment][:write_id] = @write.id
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to write_path(@write.id)
    else
      render 'new'
    end
    
  end
  
  def show
  end
  
  def edit
  end
  
  def update
  end
  
  def destroy
  end
  
private
  def set_write
    @write = Write.find_by(id: params[:write_id])
  end
  
  def comment_params
    params.require(:comment).permit(:user_id, :write_id, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	@write = Write.all
  end
end

app/controllers/userparams_controller.rb
class UserparamsController < ApplicationController
	before_action :authenticate_user!
  before_action :find_user, only: [ :show, :edit, :update, :destroy]
  def show

  end
  def new
  	@userparam = Userparam.new
  end
  def create
    @userparam = current_user.build_userparam(profile_params)
      if @userparam.save
      redirect_to userparam_path(@userparam.id)
      else
      render 'new'
  end
end
  def edit
     @userparam = current_user.userparam
  end
  def update
    @userparam = Userparam.find_by(user_id: current_user.id)
     if @userparam.update(profile_params)
      redirect_to userparam_path(@userparam.id)
     
     else
      render 'edit'
    end
  end
  def destroy
  end
  private
  def profile_params
    params.require(:userparam).permit(:user_id, :firstname, :lastname, :age, :avatar)
  end
  def find_user
    @userparam = Userparam.find_by(id: params[:id])
  end
end

app/controllers/writes_controller.rb
class WritesController < ApplicationController
before_action :authenticate_user!
before_action :find_post, only: [:show, :edit, :update, :destroy]
   def index
   end
   def new
    @write = Write.new
	end
	def create
		@write = current_user.writes.build(write_params)
  	if @write.save
  		redirect_to root_path
  	else
  		render 'new'
  	end
	end
    def show 
    	@comments = @write.comments
	end
	def edit
	end
	def update
		@write.update(write_params)
     if @write.save
     	redirect_to root_path(@write.id)
     else
     	render 'edit'
     end
	end
	def destroy
		 @write.destroy
    redirect_to root_path
	end
	def find_post
		@write = Write.find_by(id: params[:id])
	end
	private
	def write_params
		params.require(:write).permit(:title, :firstheroy, :secondheroy, :aboutstory, :body, :genre_id)	
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/userparams_helper.rb
module UserparamsHelper
end

app/helpers/writes_helper.rb
module WritesHelper
end

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/layouts/_footer.html.erb
Copirating by Zhenka 2018

app/views/layouts/_header.html.erb
<%= link_to "Головна сторінка", root_path %> |
<% if user_signed_in? %>
  <% if current_user.userparam.nil? %>
  	<%= link_to "Профіль", new_userparam_path %> |
  <% else %>
    <%= link_to "Профіль", userparam_path(current_user.id) %> |
  <% end %>
  <%= link_to "Створити історію", new_write_path %> |
  <%= link_to "Вихід", destroy_user_session_path, method: :delete %> |
<% else %>
  <%= link_to "Вхід", new_user_session_path %>
<% end %>
<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fanfik</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>

    <%- flash.each do |name, message| %>
      <p><i><%= "#{name}: #{message}" %></i></p>
    <% end %>

    <%= yield %>

    <hr>
    
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Фанфік</h1>
<p>Якщо ти хочеш почитати цікаві історії або написати свою, то реєструйся і слідкуй за оновленнями</p>
<hr>

<% if @swrite == [] %>
<% else %>
    <% @write.each do |write| %>
      <strong>Автор: </strong>
    	<%= write.user.email %>  <br />
    	<strong>Назва: </strong> <br>
   		<%= write.title %><br/>
      <strong>Жанр</strong> <br>
      <%= Genre.find_by(id: write.genre_id).try(:name) %> <br>
   		<strong>Перший головний герой: </strong> <br>
   		<%= write.firstheroy %><br/>
   		<strong>Другий головний герой: </strong> <br>
   		<%= write.secondheroy %><br/>
   		<strong>Опис: </strong> <br>
    	<%= write.aboutstory %> <br>
		<%= link_to "Читати більше", write_path(write.id) %>
   		<hr>
    <% end %>
<% end %>

app/views/userparams/edit.html.erb
<%= form_for @userparam, url: userparam_path(current_user.id) do |f| %>
<% if @userparam.errors.any? %>
  <div id="error_explanation"> 
    <h2><%= pluralize(@userparam.errors.count, "error") %> prohibited this article from being saved:</h2>
 
    <ul>
    <% @userparam.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<p>Ім'я</p><%= f.text_field :firstname%><br>
<p>Фамілія</p><%= f.text_field :lastname%><br>
<p>Вік</p><%= f.text_field :age%><br>


<%= f.submit "Зберегти" %>
	
<% end %>
  

app/views/userparams/new.html.erb
<%= form_for @userparam, url: userparams_path do |f| %>
<% if @userparam.errors.any? %>
  <div id="error_explanation"> 
    <h2><%= pluralize(@userparam.errors.count, "error") %> prohibited this article from being saved:</h2>
 
    <ul>
    <% @userparam.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>



<p><strong>Ім'я:</strong></p><%= f.text_field :firstname%><br>
<p><strong>Прізвище</strong></p><%= f.text_field :lastname%><br>
<p><strong>Вік</strong></p><%= f.text_field :age%><br>
<strong>Аватар</strong><%= f.file_field :avatar %>
<%= f.submit "Створити" %>
	
<% end %>

app/views/userparams/show.html.erb
<hr>
<%= link_to "Назад", root_path %><br />
<hr>
<h1>Це твій профіль</h1>
<%= image_tag @userparam.avatar.url(:thumb) %> <br>
Ім'я: <%= @userparam.firstname %><br />
Фамілія:<%= @userparam.lastname %><br />
Вік: <%= @userparam.age %><br />

<%= link_to "Редагувати", edit_userparam_path(current_user.id) %><br />

app/views/writes/edit.html.erb
<%= form_for @write, url: write_path(@write.id) do |f| %>
<% if @write.errors.any? %>
  <div id="error_explanation"> 
    <h2><%= pluralize(@write.errors.count, "error") %> prohibited this article from being saved:</h2>
 
    <ul>
    <% @write.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>



<p>Назва</p>
<%= f.text_field :title%><br>
<p>Жанр</p> <%= f.select :genre_id  , Genre.all.collect {|p| [ p.name, p.id ]}, :prompt => 'Оберіть жанр'%> <br>
<p>Перший головний герой</p>
<%= f.text_field :firstheroy%><br>
<p>Другий головний герой</p>
<%= f.text_field :secondheroy%><br>
<p>Опис</p>
<%= f.text_area :aboutstory, size: "60x10"%><br>
<p>Текст</p>
<%= f.text_area :body, size: "150x80"%><br>

<%= f.submit "Зберегти" %>
	
<% end %>

app/views/writes/index.html.erb
<h1>Writes#index</h1>
<p>Find me in app/views/writes/index.html.erb</p>

app/views/writes/new.html.erb
<%= form_for @write, url: writes_path do |f| %>
<% if @write.errors.any? %>
  <div id="error_explanation"> 
    <h2><%= pluralize(@write.errors.count, "error") %> prohibited this article from being saved:</h2>
 
    <ul>
    <% @write.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<p>Назва історії</p><%= f.text_field :title %><br>
<p>Жанр</p> <%= f.select :genre_id  , Genre.all.collect {|p| [ p.name, p.id ]}, :prompt => 'Оберіть жанр'%> <br>
<p>Перший головний герой</p><%= f.text_field :firstheroy %><br>
<p>Другий головний герой</p><%= f.text_field :secondheroy %><br>
<p>Короткий опис</p><%= f.text_area :aboutstory, size: "60x10" %><br />
<p>Текст</p><%= f.text_area :body, size: "150x80" %><br />
<%= f.submit "Створити" %>
	
<% end %>

app/views/writes/show.html.erb
Автор: <%= @write.user.email %><br />
Назва:<%= @write.title %><br />
Жанр:  <%= Genre.find_by(id: @write.genre_id).try(:name) %> <br>
Перший головний герой:<%= @write.firstheroy %><br />
Другий головний герой:<%= @write.secondheroy %><br />
Опис:<%= @write.aboutstory %><br />
Текст:<%= @write.body %><br />

<% if @write.user_id == current_user.id %>
<hr>
<%= link_to "Змінити", edit_write_path(@write.id) %> |
<%= link_to "Видалити", write_path(@write.id), method: :delete %><br />
<% end %>

<hr>

<% @comments.each do |comment| %>
<strong>User <%= comment.user.userparam.firstname %> write </strong><br>
<%= comment.body %> <br>
<hr>
<% end %>
<h2>Write comment here</h2>
<%= form_for :comment, url: write_comments_path(@write.id) do |f| %>
<p>Body</p><%= f.text_area :body, size: "15x9" %><br />
<%= f.submit "Create" %>
<% end %>